# pyproject.toml
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent_architect"
version = "0.1.0"
description = "Agent architecture abstractions"
requires-python = ">=3.8"
license = {text = "MIT"}